### ISSUE TITLE
Am I out of luck for a disconnected OpenShift instance?

### ISSUE THREAD

**Issue by joe-eklund** [tableau/tableau-server-in-kubernetes#21]
Per [this documentation](https://help.tableau.com/current/server-linux/en-us/server-in-container.htm), it seems that Tableau server does not support license activation on an air gapped network while running in a container.

Is this still true? Like my title states, I want to deploy Tableau Server on an air gapped OpenShift instance, and I want to know if I am on a fool's errand before I go too far down the path of attempting to deploy it. 

If air gapped deployment on OCP is truly not possible and there exist no workarounds, are there any plans to have this capability in the future?

Thank you!

**Comment by shlomitubul** [comment]
I think it is not supported:

https://help.tableau.com/current/server-linux/en-us/server-in-container.htm#:~:text=Tableau%20Server%20in%20a%20Container%20only,for%20Tableau%20Server%20in%20a%20Container.

**Comment by joe-eklund** [comment]
Thanks for the info.
