### ISSUE TITLE
Tableau container logging secrets

### ISSUE THREAD

**Issue by renannprado** [tableau/tableau-server-in-kubernetes#5]
As part of the startup of tableau's container, it will print all variables in the `.env` which may contain secrets. That's probably due to the script having `-x` set.

I didn't know where to open this issue, so I'm sorry if that's the wrong place.

**Comment by caleb15** [comment]
When reporting security issues the correct place to report it to is the security group email of the company who has the vulnerability. That way hackers (who might be reading the public github issues) don't notice a vulnerability. If you fail to get a email back within a reasonable timeframe after following up, reporting publicly is acceptable.

https://www.tableau.com/security

"All product security concerns should be reported by emailing [security@salesforce.com](mailto:security@salesforce.com).  Please review the [following guide](https://help.salesforce.com/s/articleView?language=en_US&type=1&id=000320207) before submitting findings to Salesforce.  Please reach out to your Account Manager, Pre-sales Rep, or Customer Success Manager for answers to security questionnaires."

**Comment by caleb15** [comment]
just following up on this, did they respond to your email?

**Comment by caleb15** [comment]
I reported this to security@salesforce.com. Looks like this is fixed if you build your image with the latest version of tableau-server-container-setup-tool
