### ISSUE TITLE
Tableau Kubernetes Deployment Issue

### ISSUE THREAD

**Issue by srikarganti** [tableau/tableau-server-in-kubernetes#6]
Can anyone assist me with this issue I'm facing while deploying tableau in Kubernetes?

I'm trying to deploy a single node using the template. But unfortunately, when I run the deployment I'm getting insufficient CPU and memory issues. I'm using m5X4large Amazon Linux instance that has 16vcpus and 64GB memory. I did specify the same in my YAML file. 

Error: 
"Unable to schedule pod; no fit; waiting" pod="tableau-server-ns/tableau-deployment-7f8b674dbb-qfql9" err="0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory."

Name:           tableau-deployment-7f8b674dbb-qfql9
Namespace:      tableau-server-ns
Priority:       0
Node:           <none>
Labels:         app=tableau-server
                pod-template-hash=7f8b674dbb
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/tableau-deployment-7f8b674dbb
Containers:
  tableau-repo:
    Image:      <I gave my image here>
    Port:       8080/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     16
      memory:  64Gi
    Requests:
      cpu:      16
      memory:   64Gi
    Liveness:   exec [/bin/sh -c /docker/alive-check] delay=600s timeout=1s period=60s #success=1 #failure=3
    Readiness:  exec [/bin/sh -c /docker/server-ready-check] delay=360s timeout=1s period=30s #success=1 #failure=3
    Environment:
      LICENSE_KEY:          <set to the key 'LICENSE_KEY' in secret 'tableau-secrets'>          Optional: false
      TABLEAU_USERNAME:     <set to the key 'TABLEAU_USERNAME' in secret 'tableau-secrets'>     Optional: false
      TABLEAU_PASSWORD:     <set to the key 'TABLEAU_PASSWORD' in secret 'tableau-secrets'>     Optional: false
      TSM_REMOTE_PASSWORD:  <set to the key 'TSM_REMOTE_PASSWORD' in secret 'tableau-secrets'>  Optional: false
    Mounts:
      /docker/config/config.json from configmount (rw,path="config.json")
      /var/opt/tableau from datamount (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-82wtz (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  configmount:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      configfile
    Optional:  false
  datamount:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir
    ReadOnly:   false
  kube-api-access-82wtz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  24s (x66 over 65m)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory.

**Comment by mjschuurman** [comment]
Not the entire 64GB RAM and the entire CPU is available in kubernetes, things such as: kernel, mandatory containers and the kubernetes process itself also take up memory. I would lower the requests to 50GB RAM and CPU as well.

**Comment by srikarganti** [comment]
Thanks, @mjschuurman. I took your suggestion and it resolved my issue.
